[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

"""
body = """
{% for group, group_commits in commits | group_by(attribute="group") %}
    {% set group_clean = group | striptags | trim %}
    {% if group_clean == "Other Commits" %}
<details>
<summary>Other Commits ({{ group_commits | length }})</summary>
    {% for commit in group_commits %}
* {{ commit.message | split(pat="\n") | first | trim | upper_first }}\
        {% if commit.remote.username %} (@{{ commit.remote.username }}){% endif %}\
        {% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{% endif %}
    {% endfor %}
</details>
    {% else %}
    {% set group_name = group | striptags | trim | upper_first %}
    ### {{ group_name }}
    {% for commit in group_commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | split(pat="\n") | first | trim | upper_first }}\
            {% if commit.remote.username %} (@{{ commit.remote.username }}){% endif %}\
            {% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{% endif %}\
            {%- if commit.body and commit.body | trim != "" %}{% for line in commit.body | trim | split(pat="\n") -%}{% if line | trim != "" %}
> {{ line | trim }}{% endif %}{% endfor %}{% elif commit.message | split(pat="\n") | length > 1 %}{% for line in commit.message | split(pat="\n") | slice(start=1) -%}{% if line | trim != "" %}
> {{ line | trim }}{% endif %}{% endfor %}{% endif %}
    {% endfor %}
    {% endif %}
{% endfor %}
{% if github.contributors %}
    {% set first_time = github.contributors | filter(attribute="is_first_time", value=true) %}
    {% if first_time | length > 0 %}
### New Contributors
    {% for contributor in first_time %}
        {% if contributor.pr_number %}
* @{{ contributor.username }} made their first contribution in #{{ contributor.pr_number }}
        {% else %}
* @{{ contributor.username }} made their first contribution
        {% endif %}
    {% endfor %}
    {% endif %}
{% endif %}
"""
trim = true
postprocessors = [
  { pattern = '<REPO>', replace = "https://github.com/abdullah-albanna/rusbmux" },
  { pattern = '(?m)^> ', replace = '  > ' },
]

[git]
conventional_commits = true
filter_unconventional = false
protect_breaking_commits = true
filter_commits = true
commit_preprocessors = [
  { pattern = '^fix:?$', replace = '[internal] fix' },
  { pattern = '(?i)^(typo|wip|bump|update|todo|temp)', replace = '[internal] $0' },
  { pattern = '(?i)^(minor|small fix|fix)$', replace = '[internal] $0' },
  { pattern = '^chore\(deps', replace = '[internal] $0' },
  { pattern = '^chore\(release', replace = '[internal] $0' },
  { pattern = '^\.$', replace = '[internal] .' },
  { pattern = '^Merge (pull request|branch)', replace = '[internal] $0' },
  { pattern = '\(#(\d+)', replace = "([#${1}](<REPO>/issues/${1}))" },
]
commit_parsers = [
  { message = "^\\[internal\\]", skip = true },
  { message = "^feat", group = "<!-- 00 -->Features" },
  { message = "^fix", group = "<!-- 01 -->Bug Fixes" },
  { message = "^docs", group = "<!-- 02 -->Documentation" },
  { message = "^perf", group = "<!-- 03 -->Performance" },
  { message = "^refactor", group = "<!-- 04 -->Refactoring" },
  { message = "^test", group = "<!-- 06 -->Testing" },
  { message = "^build", group = "<!-- 07 -->Build System" },
  { message = "^ci", group = "<!-- 08 -->Continuous Integration" },
  { message = "^revert", group = "<!-- 09 -->Reverts" },
  { message = "^chore\\(deps", skip = true },
  { message = "^chore\\(release", skip = true },
  { message = "^chore", group = "<!-- 10 -->Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 11 -->Security" },
  { message = ".*", group = "<!-- 12 -->Other Commits" },
]
link_parsers = [
  { pattern = "#(\\d+)", text = "#$1", href = "https://github.com/abdullah-albanna/rusbmux/issues/$1" },
]
topo_order_commits = true
sort_commits = "oldest"

[remote.github]
owner = "abdullahalternative"
repo = "rusbmux-cli-test"
