#!/bin/bash
set -e

if [ "$1" = configure ]; then
  if systemctl --version >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl enable rusbmux || true
    systemctl restart rusbmux || true
  fi
fi

exit 0
