#!/bin/bash
set -e

if [ "$1" = configure ]; then
    if systemctl --version >/dev/null 2>&1; then
        mkdir -p /usr/lib/systemd/system/
        cp /usr/share/doc/rusbmux/rusbmux.service /usr/lib/systemd/system/rusbmux.service
        systemctl daemon-reload
        systemctl enable rusbmux || true
        systemctl start rusbmux || true
    fi
fi

exit 0
