#!/bin/bash
set -e

case $1 in
    remove|upgrade)
        if systemctl --version >/dev/null 2>&1; then
            systemctl stop rusbmux || true
            systemctl disable rusbmux || true
            rm -f /lib/systemd/system/rusbmux.service
            rm -f /usr/lib/systemd/system/rusbmux.service
            systemctl daemon-reload || true
        fi
        ;;
esac

exit 0
